### ISSUE TITLE
Decide whether to use modal for details or simple pane

### ISSUE THREAD

**Issue by mstimberg** [OCNS/simselect#26]
By accident, I committed 8583e2d directly to main, but of course it can be easily reverted. It replaces the modal overlay window by a simple pane below the simulator list which I think is better for various reasons. In particular, it doesn't hide the list.

**Comment by sanjayankur31** [comment]
I think the simple pane looks really nice. I don't see what advantage the modal gives us. As you've noted, if anything, it hides the list. So instead of a user needing one click to see another entry, they need two---one to close the modal, and then another to select another entry.

+1 to simple pane

**Comment by ree-gupta** [comment]
I am sorry for catching up with all the awesome progress only now. I agree with Ankur, the current layout with simple pane is much nicer and easier to navigate.

+1!
